language: node_js
node_js:
- 6
- 7
deploy:
  provider: heroku
  api_key:
    secure: gWA/RNCzxN8kQQRfGIaLmxW91/yh+MaaISxxLBlVnjUHl5jdxaWPUDC8ehbuzlhefRL95G38yQR5AsWjq6swvxnPXKVLP0R+V+jD4L3EqMsB4WzEdcISQzl6u0DnEEc0E52taNrHA7pIt7bNqjuzZVhW1YgLELx1k/Ii7e5WEefVL00DdgcRRZlaLPYXxwfggF+sYZ+QfWGny0cqNFH5v5434IP2zHD4l0GYjnrVRHT5dKWuwMHlGOwX9Z+bpgGXAkeASqEeCg8LGHC6Rqj5j6hIJqEE0+q6wccKN0vAJAFQtnXH43SYbp3Xl1cCUcJnuWNEODNtGrZse75llCQHVrC7k8wEjll/HzVnHkjhJPQmMYB8Q9ObLMF/uiO+lKrTe5jZIs18cyKquvfP15HqD5goOp96g+SVxbvtHjzDKVd7KZ1nIMsXlzWPe/rlF5BSQtH9XVmAR+GNB0FwfmJ26r58B2gOR8sQdkkRvaj+HE5DU0rRYZA8BT1qRAskOGrIvere9ENis+L+qGHlZe5IO8pqiwimP1szIX4VSwi+We5geUXUTMJ9JeWt1IQRmQVSnk4Ki6HSPWGQCuhnu5aBgr2CplwuqDnDWuCigwRRVMwDAysVM5zY/OYByKdf7wSUb++fkFIT0jAF3DKLvxi+qoq/RkOGbY483wRXOdnp5v0=
  app: ci-smart-bot