language: node_js
node_js:
- 6
- 7
deploy:
  provider: heroku
  api_key:
    secure: Bn8oxaDC6D8Dz5pRmkcTpRUJvEEP1uvoTypCTqYJH9R0rwLKTO6Lak7VJCU70c5yiFlRfF2WoXCUWKarNWQuRimMdYLJneEiKQkE4Irx1RP4bFb+kKaUYDmu0v3cKndlkj53324+ElrPMjeIWUMCpnfI7d3J8W03ukehfoGNg1kTGIb7eBo0Xpl9PKnabb/sC5T+YG6opRnto+z215l8emY01qeHmbEwbcLqgplpDmWxWYA4c05P3Nz8iJQQbMdQUFWePRytA0OUhVml1y4d9UqRBteLHM8av3e7IWxOcZ4fvxJtjl+czyrBxx6HIBsZRycuPGjL6HZ66LuhL8UYLi/GJchyqgHSQuxcNOU3Plt3byGYVmJjhJ+GnntHli4loIjc1M22/FcmC0BKWMzhrFMHXgpSxi0BXpaHf0EoNlzAX9O7w9ttQ8BKL/WZZavbnagIlH2e5d0hYncG8d7p/FUDpwilS9F4dJEQTw7VUqX0iF9ctQcbLtm16EwKVqWlrdkMi/gxfFym91/DLUsP1HfyM4W/zK8OY+pYHHBODIIvFgsLDGP/Vd3QzLHJ3RCFYujtWSQI5pv7Kb35nrKGVDZuQcHzYt6Z+KdCLAw9oG9BYVUIndREDEqXO8Nzg/PaIL5gzDvj5Z2hbXe31aLwCyuFVBkc5QybIvZzJsIohC0=
  app: ci-smart-bot