language: node_js
node_js:
- 6
- 7
deploy:
  provider: heroku
  api_key:
    secure: VcjWYVXsPx3SFrAub1VlQrwP4IJZuIb+HQceNdoFgfNPTPHT/Mv23JJzIKMmqyB9HhIXoShhSDRgGUA1nm2fjC3X1ype9s1j3QU4SXnE8B2DIl/U/QKjU2X5FGGkSYGLDGeBQNl6OydH1ap5btzTjU/bAe4ZH/Qd23i/YZguCddcj1PcmJ9sY1sF3+SCLM9SECsoZUEtMibg+ssMzrMPyPMZiUmMMFmhJ2k/EyLIBV+FglXfdqKoAvYt2PQf5T1Jj0TeUvbLio7oqIYrTi8Izo1FbrH9a/FL7+b7EviUVZcFohU7LskMkVMxJCUGx3z0hR8O32H2cmgGTTgzd1A9hpvL7wgqd7JydV+tRri4a6n1ybpveFxZ/WvJKODvMIXr/8dOT8a5XFCZoks4meRgj8EhbJQu03kg46cC+tXSKwa3tzFTkANw1tjJuhJpeWisInRIG8GfKc3nmSTLfJ+V7n2jQAdH7B0xrERixnChuYfeSQBJH8kn9g56V6xP3Kw+gwTlhn8DhpZBvxQcZGuG9xKHFJm+Daisy6Owj55F7FwIQDGVmv8kUm/YOzbcmJJZMpoODzfE7WyOvps/zbBnQJh8MupxxgrlCsCAI164v9bzRZh+Qf10R+4FQgEiD8JDv36dqK7915EnXsaSe9mpqKEiiliXW047uRu6+qjkNvs=
  app: ci-smart-bot
