language: node_js
node_js:
- 6
- 7
deploy:
  provider: heroku
  api_key:
    secure: S0flty6ojmVeMKJh8546PnS2Mr1+dN+Y7lPKCzzGK08JSQiwTiXOw05HVcwnm0KaaePTXu8MHD2k/BbE0CKBvoGI/075eEv9HyvfEstzpB7/8cBXzOBBPyVyJsgToQj9ybwOrgSQZQLP84CvMTCOa12JAYw0Ql/KEqGmBB/0l27AMqhpg01xfiOO8axCcJDZQ/qoZZK2exlxHLMR+xBQGwWaIVc3LWX2V7umubUO0X2O2nBNS//BmKBuEP7E3tM1f/PJ74Z5g3Ts49YwlDZjixv0f2xo+++7drbfctPHbwxuGaXIZPYWC2HCpSSvkCicQfnwlFAZC6BXhdvf976Q2mQMVGXKQUNIrnzMWRXnN8nJyXwM8FbIyHPLSaYY7ynOravZRNILOCMMBrrDBlg3oinvIebPQu5U/yORTi9tiqjj4Qpfb5lcBY9X1MpywTKXHyx9BL8tpyKaG1gJESg+9RZWf8SE5ECvMDsDVqe6zUwbfppuOf5hwbpaKOAIlrXtTdJ6vQ7+ptSwUoaQm1zJKelnyrGHc6/OojqAA5olOMf6bftWRKNqtro1kOjoOiuqqfTKpIbICEefsSKLMxxJyQOE5ODtQp9oMAi7A49omi5xDwJIHHG5C7b6eZmxIJvR1msPqHu3GqzP6XWYbmkvn2DeFXluwkF3bL/KQ9b8nT4=
  app: ci-smart-bot