language: node_js
node_js:
- 6
- 7
deploy:
  provider: heroku
  api_key:
    secure: m1s+YwBi2zFioodEUZedLrV+/9+JSiecyYn3iIrWC9/ek/ABcqBrkmlX2hSZ7ahx/1ocgeB2qoLWumncL2P5Cs/lNvYDwh/+Cgb6dj/HQ/GR/62S4ykDE3ijiFdlewTecHLDTjqaouiVq7CG2yBOxftT21led9MEJa/BGp/cRjD12TvVhqHmsUYMo2h6oSu/BWci4yEWmtcgtt8MeVGIHuuaCox0Sa50jn2kzhgdCL6TU5gfXrKD65VvFr92PTEgjE6INVm07fOetb3z45FiFqfjsJn2PgF/F1kNp+ZjPRIZOpqb4z7jdecZXcC6cHUDnHLXrhIEB/+Z70ykAAlp47Lk6xQm/y3bcJuOTW+uapheWk3PMWYGUBmmOJZHD3jvRjtuc6UW2hS2sb8cwulSJy8rXs4tJz3p96CvBK+kEXkFaoqKAS45eHufeaJROTwdUssj4X8gPre4eO4dcHNmy27FREgpACXAayfmlqjDax/4154XQp8wh+KK0YE3y3sXEsN1VlymQJW3gMoBmqpzJRUoFg7x5ALRVCNtDl7dSi+CnrzrC5Qpeu/kAeokdHTA+l9lxhQ3j4j4lntZs0L3WTvrI2HeB1Dr0p3UYuWMTb4/OR7dUjawcRMy7ATjHB1RLom9rBsp86+w5c3lxP6tRVq9/aNRY1L/B43Fup2+x8E=
  app: ci-smart-bot